name: Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest

    name: Check

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: 'yarn'

      - name: Install Node Dependencies
        run: yarn install --immutable

      - name: Run TypeScript
        run: yarn types:check

      - name: Run Prettier
        run: yarn run prettier --list-different "src/**/*.{js,ts,tsx}"
