name: Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install Node Dependencies
        run: yarn install --immutable

      - name: Run TypeScript
        run: yarn types:check

      - name: Run ESLint
        run: yarn lint

      - name: Run Prettier
        run: yarn format:check
