name: Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    name: Check

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore Yarn Cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-12-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-12-

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Node Dependencies
        run: yarn install

      - name: Run TypeScript
        run: yarn run tsc --noEmit

      - name: Run Prettier
        run: yarn run prettier --list-different "src/**/*.{js,ts,tsx}"
